// Package docs_salesforce Code generated by swaggo/swag. DO NOT EDIT
package docs_salesforce

import "github.com/swaggo/swag"

const docTemplatesalesforce = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/salesforce/accounts/{ledgerAccountID}/balance": {
            "get": {
                "description": "Gets the available balance for a given ledger account id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "salesforce"
                ],
                "summary": "SalesforceGetBalance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ledger account id",
                        "name": "ledgerAccountID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/salesforce.BalanceResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid authentication",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Insufficient permissions (missing required scope)",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Could not find account",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/salesforce/accounts/{ledgerAccountID}/transactions": {
            "get": {
                "description": "Gets a list of transactions given a ledger account id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "salesforce"
                ],
                "summary": "SalesforceGetTransactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ledger account id",
                        "name": "ledgerAccountID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/salesforce.Transaction"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing or invalid authentication",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Insufficient permissions (missing required scope)",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Could not find account",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "salesforce.BalanceResponse": {
            "type": "object",
            "required": [
                "availableBalanceCents"
            ],
            "properties": {
                "availableBalanceCents": {
                    "description": "The account's available balance as expressed in cents.",
                    "type": "integer",
                    "example": 10000
                }
            }
        },
        "salesforce.Transaction": {
            "type": "object",
            "required": [
                "accountId",
                "amountCents",
                "date",
                "id",
                "merchant",
                "status",
                "type"
            ],
            "properties": {
                "accountId": {
                    "description": "The ledger's account id associated with the transaction",
                    "type": "string",
                    "example": "11522031"
                },
                "amountCents": {
                    "description": "The amount of funds (expressed in cents)",
                    "type": "integer",
                    "example": 10000
                },
                "date": {
                    "description": "The date of the transaction",
                    "type": "string",
                    "example": "2025-09-28T12:21:53Z"
                },
                "id": {
                    "description": "The reference id for the transaction",
                    "type": "string",
                    "example": "ledger.ach.transfer_ach_pull_1756829941484592000"
                },
                "merchant": {
                    "description": "The name associated with the debtor's account (if a credit); the name associated with the creditor's account otherwise",
                    "type": "string",
                    "example": "Alberta Bobbeth Charleson"
                },
                "status": {
                    "description": "The status of the transaction: ACTIVE, CLOSED, DORMANT, SUSPENDED",
                    "type": "string",
                    "example": "ACTIVE"
                },
                "type": {
                    "description": "The type of transaction as defined by the ledger: \"PRE_AUTH\", \"PURCHASE_WITH_CASH\", \"PURCHASE\", etc",
                    "type": "string",
                    "example": "ACH_OUT"
                }
            }
        }
    }
}`

// SwaggerInfosalesforce holds exported Swagger Info so clients can modify it
var SwaggerInfosalesforce = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "DreamFi Salesforce Integration API",
	Description:      "",
	InfoInstanceName: "salesforce",
	SwaggerTemplate:  docTemplatesalesforce,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfosalesforce.InstanceName(), SwaggerInfosalesforce)
}
