// GetCustomerBySSNRequest and GetCustomerResult structs are generated from https://apidocs.netxd.com/developers/docs/customer_apis/Get_Customer
package ledger

import (
	"braces.dev/errtrace"
	"github.com/go-playground/validator/v10"
)

type GetCustomerRequest interface {
	isGetCustomerRequest()
}

// There are three variations of GetCustomer:
// 1. GetCustomerBySSN – (Documented: https://apidocs.netxd.com/developers/docs/customer_apis/Get_Customer)
// 2. GetCustomerByCustomerNo – Undocumented
// 3. GetCustomerByEmailOrMobile – Undocumented
type GetCustomerBySSNRequest struct {
	Identification IdentificationData `json:"Identification" validate:"required"`
}

func (GetCustomerBySSNRequest) isGetCustomerRequest() {}

type IdentificationData struct {
	Type  string `json:"type" validate:"required,oneof=TIN SSN"`
	Value string `json:"value" validate:"required"`
}

// This variation of GetCustomer is undocumented.
// The request structure is generated by referring to an existing Postman collection.
type GetCustomerByCustomerNoRequest struct {
	CustomerNumber string `json:"customerNumber" validate:"required"`
}

func (GetCustomerByCustomerNoRequest) isGetCustomerRequest() {}

// This variation of GetCustomer is undocumented.
// The request structure is generated by referring to an existing Postman collection.
type GetCustomerByContactRequest struct {
	Contact Contact `json:"contact"`
}

func (GetCustomerByContactRequest) isGetCustomerRequest() {}

type Contact struct {
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
}

type GetCustomerResult struct {
	Id                string `json:"Id"`
	Type              string `json:"Type"`
	DOB               string `json:"DOB"`
	Title             string `json:"Title"`
	FirstName         string `json:"FirstName"`
	LastName          string `json:"LastName"`
	Gender            string `json:"Gender"`
	MonthlyProjection struct {
		Amount   int64  `json:"Amount"`
		Currency string `json:"Currency"`
	} `json:"MonthlyProjection"`
	// In the documentation, `Identification` is struct but the response returns slice of struct
	// Changing it to slice of struct  to avoid unmarshal error
	Identification []struct {
		Type  string `json:"Type"`
		Value string `json:"Value"`
	} `json:"Identification"`
	Contact struct {
		PhoneNumber string `json:"PhoneNumber"`
		Email       string `json:"Email"`
	} `json:"Contact"`
	Address struct {
		AddressLine1 string `json:"AddressLine1"`
		City         string `json:"City"`
		State        string `json:"State"`
		Country      string `json:"Country"`
		Zip          string `json:"Zip"`
	} `json:"Address"`
	Status string `json:"Status"`
	// Creating a separate struct for Account instead of an inline definition to enable reusability
	Accounts     []Account `json:"accounts"`
	CustomerData struct {
		Name string `json:"Name"`
	} `json:"CustomerData"`
}

type Account struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	NickName    string `json:"nickName"`
	Number      string `json:"number"`
	CreatedDate string `json:"createdDate"`
	UpdatedDate string `json:"updatedDate"`
	// In the documentation, `Balance` and `HoldBalance` are of type string, but the response returns them as int/float
	// Changing it to float64 to avoid unmarshal error
	Balance         float64 `json:"balance"`
	HoldBalance     float64 `json:"holdBalance"`
	CustomerID      string  `json:"customerID"`
	InstitutionName string  `json:"institutionName,omitempty"`
	AccountCategory string  `json:"accountCategory"`
	AccountType     string  `json:"accountType"`
	Currency        string  `json:"currency"`
	Status          string  `json:"status"`
	InstitutionID   string  `json:"institutionID"`
	GlAccount       string  `json:"glAccount"`
	IsVerify        bool    `json:"isVerify"`
	LedgerBalance   float64 `json:"ledgerBalance"`
	PreAuthBalance  float64 `json:"preAuthBalance"`
	AccrualBalance  float64 `json:"accrualBalance"`
}

// Keeping the request parameter type as an interface so the same function can be used for all three variations of GetCustomer
func (c *NetXDLedgerApiClient) GetCustomer(req GetCustomerRequest) (NetXDApiResponse[GetCustomerResult], error) {
	validate := validator.New()
	if err := validate.Struct(req); err != nil {
		return NetXDApiResponse[GetCustomerResult]{}, errtrace.Wrap(err)
	}
	var response NetXDApiResponse[GetCustomerResult]
	err := c.call("CustomerService.GetCustomer", c.url, req, &response)
	return response, errtrace.Wrap(err)
}

func BuildGetCustomerBySSNPayload(ssn string) *GetCustomerBySSNRequest {
	payload := GetCustomerBySSNRequest{
		Identification: IdentificationData{
			Type:  "SSN",
			Value: ssn,
		},
	}
	return &payload
}

func BuildGetCustomerByCustomerNoPayload(customerNo string) *GetCustomerByCustomerNoRequest {
	payload := GetCustomerByCustomerNoRequest{
		CustomerNumber: customerNo,
	}
	return &payload
}

func BuildGetCustomerByContactPayload(email, phoneNumber string) *GetCustomerByContactRequest {
	payload := GetCustomerByContactRequest{
		Contact: Contact{
			Email:       email,
			PhoneNumber: phoneNumber,
		},
	}
	return &payload
}
