// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: audit_service.proto

package gateway

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GwAuditService_GetAudits_FullMethodName = "/gateway.v1.GwAuditService/GetAudits"
)

// GwAuditServiceClient is the client API for GwAuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GwAuditServiceClient interface {
	GetAudits(ctx context.Context, in *GetAuditsRequest, opts ...grpc.CallOption) (*GetAuditsResponse, error)
}

type gwAuditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGwAuditServiceClient(cc grpc.ClientConnInterface) GwAuditServiceClient {
	return &gwAuditServiceClient{cc}
}

func (c *gwAuditServiceClient) GetAudits(ctx context.Context, in *GetAuditsRequest, opts ...grpc.CallOption) (*GetAuditsResponse, error) {
	out := new(GetAuditsResponse)
	err := c.cc.Invoke(ctx, GwAuditService_GetAudits_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GwAuditServiceServer is the server API for GwAuditService service.
// All implementations must embed UnimplementedGwAuditServiceServer
// for forward compatibility
type GwAuditServiceServer interface {
	GetAudits(context.Context, *GetAuditsRequest) (*GetAuditsResponse, error)
	mustEmbedUnimplementedGwAuditServiceServer()
}

// UnimplementedGwAuditServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGwAuditServiceServer struct {
}

func (UnimplementedGwAuditServiceServer) GetAudits(context.Context, *GetAuditsRequest) (*GetAuditsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudits not implemented")
}
func (UnimplementedGwAuditServiceServer) mustEmbedUnimplementedGwAuditServiceServer() {}

// UnsafeGwAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GwAuditServiceServer will
// result in compilation errors.
type UnsafeGwAuditServiceServer interface {
	mustEmbedUnimplementedGwAuditServiceServer()
}

func RegisterGwAuditServiceServer(s grpc.ServiceRegistrar, srv GwAuditServiceServer) {
	s.RegisterService(&GwAuditService_ServiceDesc, srv)
}

func _GwAuditService_GetAudits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GwAuditServiceServer).GetAudits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GwAuditService_GetAudits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GwAuditServiceServer).GetAudits(ctx, req.(*GetAuditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GwAuditService_ServiceDesc is the grpc.ServiceDesc for GwAuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GwAuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.GwAuditService",
	HandlerType: (*GwAuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAudits",
			Handler:    _GwAuditService_GetAudits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audit_service.proto",
}
