-- +goose Up

--
-- Name: cities; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.cities (
    id integer NOT NULL,
    country_code character varying(10) NOT NULL,
    state_code character varying(10) NOT NULL,
    city_name character varying(50) NOT NULL
);


ALTER TABLE public.cities OWNER TO middleware;

--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configs; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.configs (
    id integer NOT NULL,
    config_name character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    value text NOT NULL,
    user_type character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(50) NOT NULL,
    updated_at timestamp with time zone,
    updated_by character varying(50),
    CONSTRAINT configs_user_type_check CHECK (((user_type)::text = ANY ((ARRAY['ONBOARDING'::character varying, 'ONBOARDED'::character varying, 'BOTH'::character varying])::text[])))
);


ALTER TABLE public.configs OWNER TO middleware;

--
-- Name: configs_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: countries; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.countries (
    id integer NOT NULL,
    country_code character varying(10) NOT NULL,
    country_name character varying(50) NOT NULL
);


ALTER TABLE public.countries OWNER TO middleware;

--
-- Name: countries_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.countries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_account_bookmark; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.customer_account_bookmark (
    id integer NOT NULL,
    legal_rep_id character varying(50) NOT NULL,
    account_no character varying(50) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(50) NOT NULL
);


ALTER TABLE public.customer_account_bookmark OWNER TO middleware;

--
-- Name: customer_account_bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.customer_account_bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_account_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kyc_error_response; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.kyc_error_response (
    id integer NOT NULL,
    customer_no character varying(50) NOT NULL,
    kyc_response text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.kyc_error_response OWNER TO middleware;

--
-- Name: kyc_error_response_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.kyc_error_response ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kyc_error_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ledger_users; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.ledger_users (
    id integer NOT NULL,
    user_email character varying(320) NOT NULL,
    jwt_token character varying(2000) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by character varying(320) NOT NULL,
    updated_at timestamp with time zone,
    updated_by character varying(320)
);


ALTER TABLE public.ledger_users OWNER TO middleware;

--
-- Name: ledger_users_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.ledger_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ledger_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: master_user_call_record; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.master_user_call_record (
    call_sid character varying(50) NOT NULL,
    call_status character varying(255) NOT NULL,
    "to" character varying(15) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_user_call_record_call_status_check CHECK (((call_status)::text = ANY ((ARRAY['initiated'::character varying, 'ringing'::character varying, 'answered'::character varying, 'in-progress'::character varying, 'completed'::character varying, 'failed'::character varying, 'busy'::character varying, 'no-answer'::character varying])::text[])))
);


ALTER TABLE public.master_user_call_record OWNER TO middleware;

--
-- Name: master_user_logins; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.master_user_logins (
    id character varying(36) NOT NULL,
    user_id character varying(36) NOT NULL,
    ip character varying(39) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.master_user_logins OWNER TO middleware;

--
-- Name: master_user_otp; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.master_user_otp (
    otp_id character varying(36) NOT NULL,
    otp character varying(20) NOT NULL,
    otp_status character varying(20) NOT NULL,
    count integer DEFAULT 0,
    ip character varying(39) NOT NULL,
    mobile_no character varying(15),
    email character varying(320),
    user_id character varying(36) NOT NULL,
    api_path character varying(50) NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    otp_type character varying(10),
    challenge_expired_at timestamp with time zone
);


ALTER TABLE public.master_user_otp OWNER TO middleware;

--
-- Name: master_user_records; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.master_user_records (
    id character varying(36) NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    suffix character varying(10),
    email character varying(320),
    mobile_no character varying(15),
    dob date,
    password bytea,
    user_status character varying(50),
    street_address character varying(100),
    apartment_no character varying(100),
    zip_code character varying(5),
    city character varying(40),
    state character varying(2),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    ledger_password bytea,
    ledger_customer_number character varying(50),
    reset_token character varying(50),
    debtwise_customer_number integer,
    debtwise_onboarding_status character varying(255) DEFAULT 'uninitialized'::character varying NOT NULL,
    CONSTRAINT master_user_records_debtwise_onboarding_status_check CHECK (((debtwise_onboarding_status)::text = ANY ((ARRAY['complete'::character varying, 'uninitialized'::character varying, 'inProgress'::character varying])::text[])))
);


ALTER TABLE public.master_user_records OWNER TO middleware;

--
-- Name: onboarding_data; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.onboarding_data (
    temp_customer_no character varying(50) NOT NULL,
    customer_no character varying(50),
    user_details bytea NOT NULL,
    kyc_reference_no character varying(50),
    kyc_application_id character varying(100),
    kyc_details text,
    last_screen_submitted character varying(50) NOT NULL,
    extras bytea,
    initiate_kyc_resp text,
    get_kyc_documents text,
    add_customer_resp text,
    add_checking_acc_resp text,
    add_saving_acc_resp text,
    add_card_holder_resp text,
    add_card_resp text,
    end_onboarding_resp text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(50) NOT NULL,
    updated_at timestamp with time zone,
    updated_by character varying(50)
);


ALTER TABLE public.onboarding_data OWNER TO middleware;

--
-- Name: onboarding_files; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.onboarding_files (
    id integer NOT NULL,
    uuid character varying(50) NOT NULL,
    temp_customer_no character varying(50) NOT NULL,
    name character varying(250),
    type character varying(50) NOT NULL,
    url character varying(250) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(50) NOT NULL,
    updated_at timestamp with time zone,
    updated_by character varying(50)
);


ALTER TABLE public.onboarding_files OWNER TO middleware;

--
-- Name: onboarding_files_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.onboarding_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.onboarding_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plaid_items; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.plaid_items (
    id bigint NOT NULL,
    user_id character varying(36) NOT NULL,
    plaid_item_id character varying(255) NOT NULL,
    encrypted_access_token bytea NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.plaid_items OWNER TO middleware;

--
-- Name: plaid_items_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.plaid_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plaid_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sardine_kyc_data; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.sardine_kyc_data (
    id integer NOT NULL,
    session_key character varying(45) NOT NULL,
    session_key_expiry_dt timestamp with time zone,
    sardine_response text,
    user_id character varying(36) NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


ALTER TABLE public.sardine_kyc_data OWNER TO middleware;

--
-- Name: sardine_kyc_data_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.sardine_kyc_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sardine_kyc_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: signable_payloads; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.signable_payloads (
    id character varying(36) NOT NULL,
    payload text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.signable_payloads OWNER TO middleware;

--
-- Name: states; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.states (
    id integer NOT NULL,
    country_code character varying(10) NOT NULL,
    state_code character varying(10) NOT NULL,
    state_name character varying(50) NOT NULL
);


ALTER TABLE public.states OWNER TO middleware;

--
-- Name: states_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_account_card; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.user_account_card (
    id integer NOT NULL,
    card_holder_id character varying(50),
    card_id character varying(50),
    account_number character varying(45) NOT NULL,
    account_status character varying(255) NOT NULL,
    user_id character varying(36) NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT user_account_card_account_status_check CHECK (((account_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CLOSED'::character varying])::text[])))
);


ALTER TABLE public.user_account_card OWNER TO middleware;

--
-- Name: user_account_card_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.user_account_card ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_account_card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_credit_score; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.user_credit_score (
    id character varying(36) NOT NULL,
    date character varying(40) NOT NULL,
    score integer NOT NULL,
    increase integer NOT NULL,
    debtwise_customer_number integer,
    payment_history_amount real,
    payment_history_factor character varying(36),
    credit_utilization_amount real,
    credit_utilization_factor character varying(36),
    derogatory_marks_amount integer,
    derogatory_marks_factor character varying(36),
    credit_age_amount real,
    credit_age_factor character varying(36),
    credit_mix_amount integer,
    credit_mix_factor character varying(36),
    new_credit_amount real,
    new_credit_factor character varying(36),
    total_accounts_amount real,
    total_accounts_factor character varying(36),
    user_id character varying(36) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.user_credit_score OWNER TO middleware;

--
-- Name: user_otp; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.user_otp (
    id integer NOT NULL,
    customer_no character varying(50),
    receiver character varying(320) NOT NULL,
    otp character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    type character varying(20) NOT NULL,
    count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(320) NOT NULL
);


ALTER TABLE public.user_otp OWNER TO middleware;

--
-- Name: user_otp_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.user_otp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_otp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_public_keys; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.user_public_keys (
    id bigint NOT NULL,
    user_id character varying(36) NOT NULL,
    key_id character varying(50) NOT NULL,
    public_key character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    encrypted_api_key bytea
);


ALTER TABLE public.user_public_keys OWNER TO middleware;

--
-- Name: user_public_keys_id_seq; Type: SEQUENCE; Schema: public; Owner: middleware
--

ALTER TABLE public.user_public_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_public_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: middleware
--

CREATE TABLE public.users (
    customer_no character varying(50) NOT NULL,
    email character varying(320) NOT NULL,
    mobile character varying(20) NOT NULL,
    password bytea NOT NULL,
    status character varying(50) NOT NULL,
    api_name character varying(50),
    is_logged_in smallint DEFAULT 0,
    last_log_in_dt timestamp with time zone,
    current_log_in_dt timestamp with time zone,
    token_expiry_dt timestamp with time zone,
    last_log_out_dt timestamp with time zone,
    user_type character varying(50),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by character varying(50) NOT NULL,
    updated_at timestamp with time zone,
    updated_by character varying(50)
);


ALTER TABLE public.users OWNER TO middleware;

--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: configs configs_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.configs
    ADD CONSTRAINT configs_pkey PRIMARY KEY (id);


--
-- Name: countries countries_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (id);


--
-- Name: customer_account_bookmark customer_account_bookmark_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.customer_account_bookmark
    ADD CONSTRAINT customer_account_bookmark_pkey PRIMARY KEY (id);


--
-- Name: kyc_error_response kyc_error_response_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.kyc_error_response
    ADD CONSTRAINT kyc_error_response_pkey PRIMARY KEY (id);


--
-- Name: ledger_users ledger_users_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.ledger_users
    ADD CONSTRAINT ledger_users_pkey PRIMARY KEY (id);


--
-- Name: master_user_call_record master_user_call_record_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.master_user_call_record
    ADD CONSTRAINT master_user_call_record_pkey PRIMARY KEY (call_sid);


--
-- Name: master_user_logins master_user_logins_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.master_user_logins
    ADD CONSTRAINT master_user_logins_pkey PRIMARY KEY (id);


--
-- Name: master_user_otp master_user_otp_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.master_user_otp
    ADD CONSTRAINT master_user_otp_pkey PRIMARY KEY (otp_id);


--
-- Name: master_user_records master_user_records_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.master_user_records
    ADD CONSTRAINT master_user_records_pkey PRIMARY KEY (id);


--
-- Name: onboarding_data onboarding_data_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.onboarding_data
    ADD CONSTRAINT onboarding_data_pkey PRIMARY KEY (temp_customer_no);


--
-- Name: onboarding_files onboarding_files_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.onboarding_files
    ADD CONSTRAINT onboarding_files_pkey PRIMARY KEY (id);


--
-- Name: plaid_items plaid_items_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.plaid_items
    ADD CONSTRAINT plaid_items_pkey PRIMARY KEY (id);


--
-- Name: sardine_kyc_data sardine_kyc_data_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.sardine_kyc_data
    ADD CONSTRAINT sardine_kyc_data_pkey PRIMARY KEY (id);


--
-- Name: signable_payloads signable_payloads_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.signable_payloads
    ADD CONSTRAINT signable_payloads_pkey PRIMARY KEY (id);


--
-- Name: states states_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.states
    ADD CONSTRAINT states_pkey PRIMARY KEY (id);


--
-- Name: user_account_card user_account_card_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.user_account_card
    ADD CONSTRAINT user_account_card_pkey PRIMARY KEY (id);


--
-- Name: user_credit_score user_credit_score_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.user_credit_score
    ADD CONSTRAINT user_credit_score_pkey PRIMARY KEY (id);


--
-- Name: user_otp user_otp_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.user_otp
    ADD CONSTRAINT user_otp_pkey PRIMARY KEY (id);


--
-- Name: user_public_keys user_public_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.user_public_keys
    ADD CONSTRAINT user_public_keys_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (customer_no);


--
-- Name: cities_country_code_state_code_city_name_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX cities_country_code_state_code_city_name_idx ON public.cities USING btree (country_code, state_code, city_name);


--
-- Name: configs_config_name_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX configs_config_name_idx ON public.configs USING btree (config_name);


--
-- Name: countries_country_code_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX countries_country_code_idx ON public.countries USING btree (country_code);


--
-- Name: customer_account_bookmark_legal_rep_id_account_no_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX customer_account_bookmark_legal_rep_id_account_no_idx ON public.customer_account_bookmark USING btree (legal_rep_id, account_no);


--
-- Name: master_user_logins_user_id_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE INDEX master_user_logins_user_id_idx ON public.master_user_logins USING btree (user_id);


--
-- Name: master_user_otp_user_id_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE INDEX master_user_otp_user_id_idx ON public.master_user_otp USING btree (user_id);


--
-- Name: master_user_records_email_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX master_user_records_email_idx ON public.master_user_records USING btree (email);


--
-- Name: onboarding_data_customer_no_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX onboarding_data_customer_no_idx ON public.onboarding_data USING btree (customer_no);


--
-- Name: onboarding_data_kyc_reference_no_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX onboarding_data_kyc_reference_no_idx ON public.onboarding_data USING btree (kyc_reference_no);


--
-- Name: onboarding_files_url_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX onboarding_files_url_idx ON public.onboarding_files USING btree (url);


--
-- Name: onboarding_files_uuid_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX onboarding_files_uuid_idx ON public.onboarding_files USING btree (uuid);


--
-- Name: plaid_items_plaid_item_id_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX plaid_items_plaid_item_id_idx ON public.plaid_items USING btree (plaid_item_id);


--
-- Name: plaid_items_user_id_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE INDEX plaid_items_user_id_idx ON public.plaid_items USING btree (user_id);


--
-- Name: sardine_kyc_data_user_id_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE INDEX sardine_kyc_data_user_id_idx ON public.sardine_kyc_data USING btree (user_id);


--
-- Name: states_country_code_state_code_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX states_country_code_state_code_idx ON public.states USING btree (country_code, state_code);


--
-- Name: user_account_card_card_hol91cc9-b716-451c-bace-3e5b618f42cc_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX "user_account_card_card_hol91cc9-b716-451c-bace-3e5b618f42cc_idx" ON public.user_account_card USING btree (card_holder_id, card_id, user_id, account_number);


--
-- Name: user_account_card_user_id_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE INDEX user_account_card_user_id_idx ON public.user_account_card USING btree (user_id);


--
-- Name: user_credit_score_user_id_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE INDEX user_credit_score_user_id_idx ON public.user_credit_score USING btree (user_id);


--
-- Name: user_otp_type_receiver_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX user_otp_type_receiver_idx ON public.user_otp USING btree (type, receiver);


--
-- Name: user_public_keys_public_key_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE UNIQUE INDEX user_public_keys_public_key_idx ON public.user_public_keys USING btree (public_key);


--
-- Name: user_public_keys_user_id_idx; Type: INDEX; Schema: public; Owner: middleware
--

CREATE INDEX user_public_keys_user_id_idx ON public.user_public_keys USING btree (user_id);


--
-- Name: master_user_logins master_user_logins_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.master_user_logins
    ADD CONSTRAINT master_user_logins_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.master_user_records(id);


--
-- Name: master_user_otp master_user_otp_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.master_user_otp
    ADD CONSTRAINT master_user_otp_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.master_user_records(id);


--
-- Name: plaid_items plaid_items_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.plaid_items
    ADD CONSTRAINT plaid_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.master_user_records(id);


--
-- Name: sardine_kyc_data sardine_kyc_data_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.sardine_kyc_data
    ADD CONSTRAINT sardine_kyc_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.master_user_records(id);


--
-- Name: user_account_card user_account_card_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.user_account_card
    ADD CONSTRAINT user_account_card_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.master_user_records(id);


--
-- Name: user_credit_score user_credit_score_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.user_credit_score
    ADD CONSTRAINT user_credit_score_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.master_user_records(id);


--
-- Name: user_public_keys user_public_keys_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: middleware
--

ALTER TABLE ONLY public.user_public_keys
    ADD CONSTRAINT user_public_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.master_user_records(id);
