// Package visadps provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.4.1 DO NOT EDIT.
package visadps

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AuthorizationSimulatorRequestTransactionType.
const (
	TCTECOMMERCE AuthorizationSimulatorRequestTransactionType = "TCT_E_COMMERCE"
)

// AuthorizationSimulatorRequest defines model for AuthorizationSimulatorRequest.
type AuthorizationSimulatorRequest struct {
	// BillingAmount Transaction amount in cardholder's local currency.
	BillingAmount BillingAmount `json:"billingAmount"`

	// Customization Customization details.
	Customization *SimulatorCustomization `json:"customization,omitempty"`

	// PaymentInstrument Object details (card number or cardid) of the actual payment instrument used for an authorization request.
	PaymentInstrument PaymentInstrument `json:"paymentInstrument"`

	// TransactionAmount Transaction amount in merchant currency. Only applicable in case of cross-border transaction.
	TransactionAmount *TransactionAmount `json:"transactionAmount,omitempty"`

	// TransactionType Type of transaction.
	TransactionType AuthorizationSimulatorRequestTransactionType `json:"transactionType"`
}

// AuthorizationSimulatorRequestTransactionType Type of transaction.
type AuthorizationSimulatorRequestTransactionType string

// AuthorizationSimulatorResponse Response object that contains details for this resource.
type AuthorizationSimulatorResponse struct {
	// Approved Indicates if transaction is approved.
	Approved bool `json:"approved"`

	// Reason Reason why transaction was declined.
	Reason *string `json:"reason,omitempty"`

	// TransactionAmount Transaction amount in merchant currency. Only applicable in case of cross-border transaction.
	TransactionAmount *float32 `json:"transactionAmount,omitempty"`

	// TransactionId GUID. Unique ID, generated by client, for a given transaction. Used to prevent duplicate entries.
	TransactionId string `json:"transactionId"`
}

// BillingAddress Address details.
type BillingAddress struct {
	// City City.
	City string `json:"city"`

	// CountryCode 3-character ISO country code.
	CountryCode string `json:"countryCode"`

	// Line1 Address line 1.
	Line1 string `json:"line1"`

	// Line2 Address line 2.
	Line2 *string `json:"line2,omitempty"`

	// PostalCode Postal code.
	PostalCode string `json:"postalCode"`

	// Region ISO region code recommended..
	Region *string `json:"region,omitempty"`
}

// BillingAmount Transaction amount in cardholder's local currency.
type BillingAmount struct {
	// Amount Transaction amount in cardholder’s local currency.
	Amount float32 `json:"amount"`

	// CurrencyCode 3-character ISO currency code.
	CurrencyCode *string `json:"currencyCode,omitempty"`
}

// CardHolderInfo Cardholder details. .
type CardHolderInfo struct {
	// BillingAddress Address details.
	BillingAddress BillingAddress `json:"billingAddress"`

	// FirstName First name.
	FirstName string `json:"firstName"`

	// LastName Last name.
	LastName string `json:"lastName"`

	// MiddleInitial Middle initial.
	MiddleInitial *string `json:"middleInitial,omitempty"`
}

// ClearingCustomization Customization details.
type ClearingCustomization struct {
	// MultiClearingInfo Multiclearing details.
	MultiClearingInfo *MultiClearingInfo `json:"multiClearingInfo,omitempty"`
}

// ClearingSimulatorRequest defines model for ClearingSimulatorRequest.
type ClearingSimulatorRequest struct {
	// BillingAmount Transaction amount in cardholder's local currency.
	BillingAmount BillingAmount `json:"billingAmount"`

	// Customization Customization details.
	Customization *ClearingCustomization `json:"customization,omitempty"`

	// OriginalTransactionId Original transaction ID returned from acquirer.
	OriginalTransactionId string `json:"originalTransactionId"`

	// TransactionAmount Transaction amount in merchant currency. Only applicable in case of cross-border transaction.
	TransactionAmount *TransactionAmount `json:"transactionAmount,omitempty"`
}

// ClearingSimulatorResponse Response object that contains details for this resource.
type ClearingSimulatorResponse struct {
	// TransactionId GUID. Unique ID, generated by Visa, for a given transaction. Used to prevent duplicate entries.
	TransactionId string `json:"transactionId"`
}

// CommonError The response error container
type CommonError struct {
	// Code HTTP response code.
	Code *int32 `json:"code,omitempty"`

	// Description Description of HTTP response code.
	Description *string `json:"description,omitempty"`

	// Details Error details.
	Details *[]CommonErrorDetails `json:"details,omitempty"`
}

// CommonErrorDetails Error details.
type CommonErrorDetails struct {
	// Attribute If error relates to specific field, name of field associated with error.
	Attribute *string `json:"attribute,omitempty"`

	// Id Unique ID to identify the error condition.
	Id *string `json:"id,omitempty"`

	// Message Detailed message describing the error.
	Message *string `json:"message,omitempty"`

	// Type Type of error returned.
	Type *string `json:"type,omitempty"`
}

// CommonResponse defines model for CommonResponse.
type CommonResponse struct {
	// Error The response error container
	Error *CommonError `json:"error"`

	// ProcessingTimeinMs Internal time taken to process a request and deliver a response, in milliseconds.
	ProcessingTimeinMs int64 `json:"processingTimeinMs"`

	// ReceivedTimestamp Date/time request was received. The value is in UTC and the format is yyyy-MM-dd'T'hh:mm:ss.SSS'Z'.
	ReceivedTimestamp string `json:"receivedTimestamp"`

	// Resource Response object that contains details for this resource.
	Resource *map[string]interface{} `json:"resource"`
}

// CommonResponseAuthorizationSimulatorResponse defines model for CommonResponseAuthorizationSimulatorResponse.
type CommonResponseAuthorizationSimulatorResponse struct {
	// Error The response error container
	Error *CommonError `json:"error"`

	// ProcessingTimeinMs Internal time taken to process a request and deliver a response, in milliseconds.
	ProcessingTimeinMs int64 `json:"processingTimeinMs"`

	// ReceivedTimestamp Date/time request was received. The value is in UTC and the format is yyyy-MM-dd'T'hh:mm:ss.SSS'Z'.
	ReceivedTimestamp string `json:"receivedTimestamp"`

	// Resource Response object that contains details for this resource.
	Resource *AuthorizationSimulatorResponse `json:"resource"`
}

// CommonResponseClearingSimulatorResponse defines model for CommonResponseClearingSimulatorResponse.
type CommonResponseClearingSimulatorResponse struct {
	// Error The response error container
	Error *CommonError `json:"error"`

	// ProcessingTimeinMs Internal time taken to process a request and deliver a response, in milliseconds.
	ProcessingTimeinMs int64 `json:"processingTimeinMs"`

	// ReceivedTimestamp Date/time request was received. The value is in UTC and the format is yyyy-MM-dd'T'hh:mm:ss.SSS'Z'.
	ReceivedTimestamp string `json:"receivedTimestamp"`

	// Resource Response object that contains details for this resource.
	Resource *ClearingSimulatorResponse `json:"resource"`
}

// CommonResponseGenerateCvv2Response defines model for CommonResponseGenerateCvv2Response.
type CommonResponseGenerateCvv2Response struct {
	// ProcessingTimeinMs Internal time taken to process a request and deliver a response, in milliseconds.
	ProcessingTimeinMs int64 `json:"processingTimeinMs"`

	// ReceivedTimestamp Date/time request was received. The value is in UTC and the format is yyyy-MM-dd'T'hh:mm:ss.SSS'Z'.
	ReceivedTimestamp string `json:"receivedTimestamp"`

	// Resource Response object that contains details for this resource.
	Resource *GenerateCvv2Response `json:"resource"`
}

// CommonResponseGenerateCvv2Response1 defines model for CommonResponseGenerateCvv2Response-1.
type CommonResponseGenerateCvv2Response1 struct {
	// Error The response error container
	Error *CommonError `json:"error"`

	// ProcessingTimeinMs Internal time taken to process a request and deliver a response, in milliseconds.
	ProcessingTimeinMs int64 `json:"processingTimeinMs"`

	// ReceivedTimestamp Date/time request was received. The value is in UTC and the format is yyyy-MM-dd'T'hh:mm:ss.SSS'Z'.
	ReceivedTimestamp string `json:"receivedTimestamp"`

	// Resource Response object that contains details for this resource.
	Resource *GenerateCvv2Response `json:"resource"`
}

// ExpirationDate Expiration date details.
type ExpirationDate struct {
	// Mm Month the card expires (01-12).
	Mm string `json:"mm"`

	// Yy Year the card expires. Last  2 digits of year, only.
	Yy string `json:"yy"`
}

// GenerateCvv2Request defines model for GenerateCvv2Request.
type GenerateCvv2Request struct {
	// ExpirationDate Expiration date details.
	ExpirationDate ExpirationDate `json:"expirationDate"`
}

// GenerateCvv2RequestV2 defines model for GenerateCvv2RequestV2.
type GenerateCvv2RequestV2 struct {
	// ExpirationDate Expiration date details.
	ExpirationDate ExpirationDate `json:"expirationDate"`

	// Last4PrimaryAccountNumber Last 4 digits of card number.
	Last4PrimaryAccountNumber string `json:"last4PrimaryAccountNumber"`
}

// GenerateCvv2Response Response object that contains details for this resource.
type GenerateCvv2Response struct {
	// Cvv2 3-digit security code.
	Cvv2 string `json:"cvv2"`
}

// MerchantInfo Merchant details.
type MerchantInfo struct {
	// MerchantCategoryCode 4-digit ISO merchant classification code that identifies the merchant by their business line.
	MerchantCategoryCode string `json:"merchantCategoryCode"`
}

// MultiClearingInfo Multiclearing details.
type MultiClearingInfo struct {
	// SequenceCount Total number of items in a multiclearing transaction.
	SequenceCount string `json:"sequenceCount"`

	// SequenceNumber Sequence number associated with each clearing item.
	SequenceNumber string `json:"sequenceNumber"`
}

// PaymentInstrument Object details (card number or cardid) of the actual payment instrument used for an authorization request.
type PaymentInstrument struct {
	// CardId Unique ID for current card.
	CardId *string `json:"cardId,omitempty"`

	// PrimaryAccountNumber Unique value used to identify a card in the system. This value is used to transact.
	PrimaryAccountNumber *string `json:"primaryAccountNumber,omitempty"`
}

// SimulatorCustomization Customization details.
type SimulatorCustomization struct {
	// CardHolderInfo Cardholder details. .
	CardHolderInfo CardHolderInfo `json:"cardHolderInfo"`

	// MerchantInfo Merchant details.
	MerchantInfo *MerchantInfo `json:"merchantInfo,omitempty"`
}

// TransactionAmount Transaction amount in merchant currency. Only applicable in case of cross-border transaction.
type TransactionAmount struct {
	// Amount Transaction amount in merchant's local currency.
	Amount float32 `json:"amount"`

	// CurrencyCode 3-character ISO currency code.
	CurrencyCode string `json:"currencyCode"`
}

// GenerateCvv2ForCardAliasIdParams defines parameters for GenerateCvv2ForCardAliasId.
type GenerateCvv2ForCardAliasIdParams struct {
	// CorrelationId Unique ID provided by caller that correlates to a specific message transmission. Used to easily find a message in the logs.
	CorrelationId *string `json:"correlation-id,omitempty"`
}

// GenerateCvv2ForCardAliasId2Params defines parameters for GenerateCvv2ForCardAliasId2.
type GenerateCvv2ForCardAliasId2Params struct {
	// CorrelationId Unique ID provided by caller that correlates to a specific message transmission. Used to easily find a message in the logs.
	CorrelationId *string `json:"correlation-id,omitempty"`
}

// AuthSimulatorParams defines parameters for AuthSimulator.
type AuthSimulatorParams struct {
	// CorrelationId Unique ID provided by caller that correlates to a specific message transmission. Used to easily find a message in the logs.
	CorrelationId *string `json:"correlation-id,omitempty"`
}

// ClearingSimulatorParams defines parameters for ClearingSimulator.
type ClearingSimulatorParams struct {
	// CorrelationId Unique ID provided by caller that correlates to a specific message transmission. Used to easily find a message in the logs.
	CorrelationId *string `json:"correlation-id,omitempty"`
}

// GenerateCvv2ForCardAliasIdJSONRequestBody defines body for GenerateCvv2ForCardAliasId for application/json ContentType.
type GenerateCvv2ForCardAliasIdJSONRequestBody = GenerateCvv2Request

// GenerateCvv2ForCardAliasId2JSONRequestBody defines body for GenerateCvv2ForCardAliasId2 for application/json ContentType.
type GenerateCvv2ForCardAliasId2JSONRequestBody = GenerateCvv2RequestV2

// AuthSimulatorJSONRequestBody defines body for AuthSimulator for application/json ContentType.
type AuthSimulatorJSONRequestBody = AuthorizationSimulatorRequest

// ClearingSimulatorJSONRequestBody defines body for ClearingSimulator for application/json ContentType.
type ClearingSimulatorJSONRequestBody = ClearingSimulatorRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GenerateCvv2ForCardAliasIdWithBody request with any body
	GenerateCvv2ForCardAliasIdWithBody(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateCvv2ForCardAliasId(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasIdParams, body GenerateCvv2ForCardAliasIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateCvv2ForCardAliasId2WithBody request with any body
	GenerateCvv2ForCardAliasId2WithBody(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasId2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateCvv2ForCardAliasId2(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasId2Params, body GenerateCvv2ForCardAliasId2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AuthSimulatorWithBody request with any body
	AuthSimulatorWithBody(ctx context.Context, params *AuthSimulatorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AuthSimulator(ctx context.Context, params *AuthSimulatorParams, body AuthSimulatorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ClearingSimulatorWithBody request with any body
	ClearingSimulatorWithBody(ctx context.Context, params *ClearingSimulatorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ClearingSimulator(ctx context.Context, params *ClearingSimulatorParams, body ClearingSimulatorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GenerateCvv2ForCardAliasIdWithBody(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateCvv2ForCardAliasIdRequestWithBody(c.Server, cardId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateCvv2ForCardAliasId(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasIdParams, body GenerateCvv2ForCardAliasIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateCvv2ForCardAliasIdRequest(c.Server, cardId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateCvv2ForCardAliasId2WithBody(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasId2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateCvv2ForCardAliasId2RequestWithBody(c.Server, cardId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateCvv2ForCardAliasId2(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasId2Params, body GenerateCvv2ForCardAliasId2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateCvv2ForCardAliasId2Request(c.Server, cardId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AuthSimulatorWithBody(ctx context.Context, params *AuthSimulatorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthSimulatorRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AuthSimulator(ctx context.Context, params *AuthSimulatorParams, body AuthSimulatorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthSimulatorRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ClearingSimulatorWithBody(ctx context.Context, params *ClearingSimulatorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClearingSimulatorRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ClearingSimulator(ctx context.Context, params *ClearingSimulatorParams, body ClearingSimulatorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClearingSimulatorRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGenerateCvv2ForCardAliasIdRequest calls the generic GenerateCvv2ForCardAliasId builder with application/json body
func NewGenerateCvv2ForCardAliasIdRequest(server string, cardId string, params *GenerateCvv2ForCardAliasIdParams, body GenerateCvv2ForCardAliasIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateCvv2ForCardAliasIdRequestWithBody(server, cardId, params, "application/json", bodyReader)
}

// NewGenerateCvv2ForCardAliasIdRequestWithBody generates requests for GenerateCvv2ForCardAliasId with any type of body
func NewGenerateCvv2ForCardAliasIdRequestWithBody(server string, cardId string, params *GenerateCvv2ForCardAliasIdParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cardId", runtime.ParamLocationPath, cardId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/forward/cardservices/v1/cards/%s/cvv2", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.CorrelationId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "correlation-id", runtime.ParamLocationHeader, *params.CorrelationId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("correlation-id", headerParam0)
		}

	}

	return req, nil
}

// NewGenerateCvv2ForCardAliasId2Request calls the generic GenerateCvv2ForCardAliasId2 builder with application/json body
func NewGenerateCvv2ForCardAliasId2Request(server string, cardId string, params *GenerateCvv2ForCardAliasId2Params, body GenerateCvv2ForCardAliasId2JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateCvv2ForCardAliasId2RequestWithBody(server, cardId, params, "application/json", bodyReader)
}

// NewGenerateCvv2ForCardAliasId2RequestWithBody generates requests for GenerateCvv2ForCardAliasId2 with any type of body
func NewGenerateCvv2ForCardAliasId2RequestWithBody(server string, cardId string, params *GenerateCvv2ForCardAliasId2Params, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cardId", runtime.ParamLocationPath, cardId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/forward/cardservices/v2/cards/%s/cvv2", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.CorrelationId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "correlation-id", runtime.ParamLocationHeader, *params.CorrelationId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("correlation-id", headerParam0)
		}

	}

	return req, nil
}

// NewAuthSimulatorRequest calls the generic AuthSimulator builder with application/json body
func NewAuthSimulatorRequest(server string, params *AuthSimulatorParams, body AuthSimulatorJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAuthSimulatorRequestWithBody(server, params, "application/json", bodyReader)
}

// NewAuthSimulatorRequestWithBody generates requests for AuthSimulator with any type of body
func NewAuthSimulatorRequestWithBody(server string, params *AuthSimulatorParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/forward/transactionsimulatorservices/v1/authorizations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.CorrelationId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "correlation-id", runtime.ParamLocationHeader, *params.CorrelationId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("correlation-id", headerParam0)
		}

	}

	return req, nil
}

// NewClearingSimulatorRequest calls the generic ClearingSimulator builder with application/json body
func NewClearingSimulatorRequest(server string, params *ClearingSimulatorParams, body ClearingSimulatorJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewClearingSimulatorRequestWithBody(server, params, "application/json", bodyReader)
}

// NewClearingSimulatorRequestWithBody generates requests for ClearingSimulator with any type of body
func NewClearingSimulatorRequestWithBody(server string, params *ClearingSimulatorParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/forward/transactionsimulatorservices/v1/clearings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.CorrelationId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "correlation-id", runtime.ParamLocationHeader, *params.CorrelationId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("correlation-id", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GenerateCvv2ForCardAliasIdWithBodyWithResponse request with any body
	GenerateCvv2ForCardAliasIdWithBodyWithResponse(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateCvv2ForCardAliasIdResponseResult, error)

	GenerateCvv2ForCardAliasIdWithResponse(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasIdParams, body GenerateCvv2ForCardAliasIdJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateCvv2ForCardAliasIdResponseResult, error)

	// GenerateCvv2ForCardAliasId2WithBodyWithResponse request with any body
	GenerateCvv2ForCardAliasId2WithBodyWithResponse(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasId2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateCvv2ForCardAliasId2ResponseResult, error)

	GenerateCvv2ForCardAliasId2WithResponse(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasId2Params, body GenerateCvv2ForCardAliasId2JSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateCvv2ForCardAliasId2ResponseResult, error)

	// AuthSimulatorWithBodyWithResponse request with any body
	AuthSimulatorWithBodyWithResponse(ctx context.Context, params *AuthSimulatorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthSimulatorResponseResult, error)

	AuthSimulatorWithResponse(ctx context.Context, params *AuthSimulatorParams, body AuthSimulatorJSONRequestBody, reqEditors ...RequestEditorFn) (*AuthSimulatorResponseResult, error)

	// ClearingSimulatorWithBodyWithResponse request with any body
	ClearingSimulatorWithBodyWithResponse(ctx context.Context, params *ClearingSimulatorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClearingSimulatorResponseResult, error)

	ClearingSimulatorWithResponse(ctx context.Context, params *ClearingSimulatorParams, body ClearingSimulatorJSONRequestBody, reqEditors ...RequestEditorFn) (*ClearingSimulatorResponseResult, error)
}

type GenerateCvv2ForCardAliasIdResponseResult struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommonResponseGenerateCvv2Response1
	JSON400      *CommonResponse
	JSON403      *CommonResponse
	JSON404      *CommonResponse
	JSON422      *CommonResponse
	JSON500      *CommonResponse
}

// Status returns HTTPResponse.Status
func (r GenerateCvv2ForCardAliasIdResponseResult) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateCvv2ForCardAliasIdResponseResult) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateCvv2ForCardAliasId2ResponseResult struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommonResponseGenerateCvv2Response
	JSON400      *struct {
		// Code HTTP response code.
		Code *string `json:"code,omitempty"`

		// Description Description of HTTP response code.
		Description *string `json:"description,omitempty"`
		Details     *[]struct {
			// Attribute If error relates to specific field, name of field associated to the error.
			Attribute *string `json:"attribute,omitempty"`

			// Id Unique ID to identify the error condition.
			Id *string `json:"id,omitempty"`

			// Message Detailed message describing the error.
			Message *string `json:"message,omitempty"`

			// Type Type of error returned.
			Type *string `json:"type,omitempty"`
		} `json:"details,omitempty"`
	}
	JSON403 *struct {
		// Code HTTP response code.
		Code *string `json:"code,omitempty"`

		// Description Description of HTTP response code.
		Description *string `json:"description,omitempty"`
		Details     *[]struct {
			// Attribute ${attribute}
			Attribute *string `json:"attribute,omitempty"`

			// Id Unique ID to identify the error condition.
			Id *string `json:"id,omitempty"`

			// Message Detailed message describing the error.
			Message *string `json:"message,omitempty"`

			// Type Type of error returned.
			Type *string `json:"type,omitempty"`
		} `json:"details,omitempty"`
	}
	JSON404 *struct {
		// Code HTTP response code.
		Code *string `json:"code,omitempty"`

		// Description Description of HTTP response code.
		Description *string `json:"description,omitempty"`
		Details     *[]struct {
			// Attribute ${attribute}
			Attribute *string `json:"attribute,omitempty"`

			// Id Unique ID to identify the error condition.
			Id *string `json:"id,omitempty"`

			// Message Detailed message describing the error.
			Message *string `json:"message,omitempty"`

			// Type Type of error returned.
			Type *string `json:"type,omitempty"`
		} `json:"details,omitempty"`
	}
	JSON422 *struct {
		// Code HTTP response code.
		Code *string `json:"code,omitempty"`

		// Description Description of HTTP response code.
		Description *string `json:"description,omitempty"`
		Details     *[]struct {
			// Attribute If error relates to specific field, name of field associated to the error.
			Attribute *string `json:"attribute,omitempty"`

			// Id Unique ID to identify the error condition.
			Id *string `json:"id,omitempty"`

			// Message Detailed message describing the error.
			Message *string `json:"message,omitempty"`

			// Type Type of error returned.
			Type *string `json:"type,omitempty"`
		} `json:"details,omitempty"`
	}
	JSON500 *struct {
		// Code HTTP response code.
		Code *string `json:"code,omitempty"`

		// Description Description of HTTP response code.
		Description *string `json:"description,omitempty"`
		Details     *[]struct {
			// Attribute ${attribute}
			Attribute *string `json:"attribute,omitempty"`

			// Id Unique ID to identify the error condition.
			Id *string `json:"id,omitempty"`

			// Message Detailed message describing the error.
			Message *string `json:"message,omitempty"`

			// Type Type of error returned.
			Type *string `json:"type,omitempty"`
		} `json:"details,omitempty"`
	}
	JSON503 *struct {
		// Code HTTP response code.
		Code *string `json:"code,omitempty"`

		// Description Description of HTTP response code.
		Description *string `json:"description,omitempty"`
		Details     *[]struct {
			// Attribute ${attribute}
			Attribute *string `json:"attribute,omitempty"`

			// Id Unique ID to identify the error condition.
			Id *string `json:"id,omitempty"`

			// Message Detailed message describing the error.
			Message *string `json:"message,omitempty"`

			// Type Type of error returned.
			Type *string `json:"type,omitempty"`
		} `json:"details,omitempty"`
	}
	JSON504 *struct {
		// Code HTTP response code.
		Code *string `json:"code,omitempty"`

		// Description Description of HTTP response code.
		Description *string `json:"description,omitempty"`
		Details     *[]struct {
			// Attribute ${attribute}
			Attribute *string `json:"attribute,omitempty"`

			// Id Unique ID to identify the error condition.
			Id *string `json:"id,omitempty"`

			// Message Detailed message describing the error.
			Message *string `json:"message,omitempty"`

			// Type Type of error returned.
			Type *string `json:"type,omitempty"`
		} `json:"details,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GenerateCvv2ForCardAliasId2ResponseResult) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateCvv2ForCardAliasId2ResponseResult) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AuthSimulatorResponseResult struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommonResponseAuthorizationSimulatorResponse
	JSON400      *CommonResponse
	JSON403      *CommonResponse
	JSON404      *CommonResponse
	JSON422      *CommonResponse
	JSON500      *CommonResponse
}

// Status returns HTTPResponse.Status
func (r AuthSimulatorResponseResult) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuthSimulatorResponseResult) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ClearingSimulatorResponseResult struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommonResponseClearingSimulatorResponse
	JSON400      *CommonResponse
	JSON403      *CommonResponse
	JSON404      *CommonResponse
	JSON422      *CommonResponse
	JSON500      *CommonResponse
}

// Status returns HTTPResponse.Status
func (r ClearingSimulatorResponseResult) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ClearingSimulatorResponseResult) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GenerateCvv2ForCardAliasIdWithBodyWithResponse request with arbitrary body returning *GenerateCvv2ForCardAliasIdResponseResult
func (c *ClientWithResponses) GenerateCvv2ForCardAliasIdWithBodyWithResponse(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateCvv2ForCardAliasIdResponseResult, error) {
	rsp, err := c.GenerateCvv2ForCardAliasIdWithBody(ctx, cardId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateCvv2ForCardAliasIdResponseResult(rsp)
}

func (c *ClientWithResponses) GenerateCvv2ForCardAliasIdWithResponse(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasIdParams, body GenerateCvv2ForCardAliasIdJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateCvv2ForCardAliasIdResponseResult, error) {
	rsp, err := c.GenerateCvv2ForCardAliasId(ctx, cardId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateCvv2ForCardAliasIdResponseResult(rsp)
}

// GenerateCvv2ForCardAliasId2WithBodyWithResponse request with arbitrary body returning *GenerateCvv2ForCardAliasId2ResponseResult
func (c *ClientWithResponses) GenerateCvv2ForCardAliasId2WithBodyWithResponse(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasId2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateCvv2ForCardAliasId2ResponseResult, error) {
	rsp, err := c.GenerateCvv2ForCardAliasId2WithBody(ctx, cardId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateCvv2ForCardAliasId2ResponseResult(rsp)
}

func (c *ClientWithResponses) GenerateCvv2ForCardAliasId2WithResponse(ctx context.Context, cardId string, params *GenerateCvv2ForCardAliasId2Params, body GenerateCvv2ForCardAliasId2JSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateCvv2ForCardAliasId2ResponseResult, error) {
	rsp, err := c.GenerateCvv2ForCardAliasId2(ctx, cardId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateCvv2ForCardAliasId2ResponseResult(rsp)
}

// AuthSimulatorWithBodyWithResponse request with arbitrary body returning *AuthSimulatorResponseResult
func (c *ClientWithResponses) AuthSimulatorWithBodyWithResponse(ctx context.Context, params *AuthSimulatorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthSimulatorResponseResult, error) {
	rsp, err := c.AuthSimulatorWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthSimulatorResponseResult(rsp)
}

func (c *ClientWithResponses) AuthSimulatorWithResponse(ctx context.Context, params *AuthSimulatorParams, body AuthSimulatorJSONRequestBody, reqEditors ...RequestEditorFn) (*AuthSimulatorResponseResult, error) {
	rsp, err := c.AuthSimulator(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthSimulatorResponseResult(rsp)
}

// ClearingSimulatorWithBodyWithResponse request with arbitrary body returning *ClearingSimulatorResponseResult
func (c *ClientWithResponses) ClearingSimulatorWithBodyWithResponse(ctx context.Context, params *ClearingSimulatorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClearingSimulatorResponseResult, error) {
	rsp, err := c.ClearingSimulatorWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClearingSimulatorResponseResult(rsp)
}

func (c *ClientWithResponses) ClearingSimulatorWithResponse(ctx context.Context, params *ClearingSimulatorParams, body ClearingSimulatorJSONRequestBody, reqEditors ...RequestEditorFn) (*ClearingSimulatorResponseResult, error) {
	rsp, err := c.ClearingSimulator(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClearingSimulatorResponseResult(rsp)
}

// ParseGenerateCvv2ForCardAliasIdResponseResult parses an HTTP response from a GenerateCvv2ForCardAliasIdWithResponse call
func ParseGenerateCvv2ForCardAliasIdResponseResult(rsp *http.Response) (*GenerateCvv2ForCardAliasIdResponseResult, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateCvv2ForCardAliasIdResponseResult{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommonResponseGenerateCvv2Response1
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGenerateCvv2ForCardAliasId2ResponseResult parses an HTTP response from a GenerateCvv2ForCardAliasId2WithResponse call
func ParseGenerateCvv2ForCardAliasId2ResponseResult(rsp *http.Response) (*GenerateCvv2ForCardAliasId2ResponseResult, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateCvv2ForCardAliasId2ResponseResult{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommonResponseGenerateCvv2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			// Code HTTP response code.
			Code *string `json:"code,omitempty"`

			// Description Description of HTTP response code.
			Description *string `json:"description,omitempty"`
			Details     *[]struct {
				// Attribute If error relates to specific field, name of field associated to the error.
				Attribute *string `json:"attribute,omitempty"`

				// Id Unique ID to identify the error condition.
				Id *string `json:"id,omitempty"`

				// Message Detailed message describing the error.
				Message *string `json:"message,omitempty"`

				// Type Type of error returned.
				Type *string `json:"type,omitempty"`
			} `json:"details,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			// Code HTTP response code.
			Code *string `json:"code,omitempty"`

			// Description Description of HTTP response code.
			Description *string `json:"description,omitempty"`
			Details     *[]struct {
				// Attribute ${attribute}
				Attribute *string `json:"attribute,omitempty"`

				// Id Unique ID to identify the error condition.
				Id *string `json:"id,omitempty"`

				// Message Detailed message describing the error.
				Message *string `json:"message,omitempty"`

				// Type Type of error returned.
				Type *string `json:"type,omitempty"`
			} `json:"details,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			// Code HTTP response code.
			Code *string `json:"code,omitempty"`

			// Description Description of HTTP response code.
			Description *string `json:"description,omitempty"`
			Details     *[]struct {
				// Attribute ${attribute}
				Attribute *string `json:"attribute,omitempty"`

				// Id Unique ID to identify the error condition.
				Id *string `json:"id,omitempty"`

				// Message Detailed message describing the error.
				Message *string `json:"message,omitempty"`

				// Type Type of error returned.
				Type *string `json:"type,omitempty"`
			} `json:"details,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			// Code HTTP response code.
			Code *string `json:"code,omitempty"`

			// Description Description of HTTP response code.
			Description *string `json:"description,omitempty"`
			Details     *[]struct {
				// Attribute If error relates to specific field, name of field associated to the error.
				Attribute *string `json:"attribute,omitempty"`

				// Id Unique ID to identify the error condition.
				Id *string `json:"id,omitempty"`

				// Message Detailed message describing the error.
				Message *string `json:"message,omitempty"`

				// Type Type of error returned.
				Type *string `json:"type,omitempty"`
			} `json:"details,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			// Code HTTP response code.
			Code *string `json:"code,omitempty"`

			// Description Description of HTTP response code.
			Description *string `json:"description,omitempty"`
			Details     *[]struct {
				// Attribute ${attribute}
				Attribute *string `json:"attribute,omitempty"`

				// Id Unique ID to identify the error condition.
				Id *string `json:"id,omitempty"`

				// Message Detailed message describing the error.
				Message *string `json:"message,omitempty"`

				// Type Type of error returned.
				Type *string `json:"type,omitempty"`
			} `json:"details,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			// Code HTTP response code.
			Code *string `json:"code,omitempty"`

			// Description Description of HTTP response code.
			Description *string `json:"description,omitempty"`
			Details     *[]struct {
				// Attribute ${attribute}
				Attribute *string `json:"attribute,omitempty"`

				// Id Unique ID to identify the error condition.
				Id *string `json:"id,omitempty"`

				// Message Detailed message describing the error.
				Message *string `json:"message,omitempty"`

				// Type Type of error returned.
				Type *string `json:"type,omitempty"`
			} `json:"details,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 504:
		var dest struct {
			// Code HTTP response code.
			Code *string `json:"code,omitempty"`

			// Description Description of HTTP response code.
			Description *string `json:"description,omitempty"`
			Details     *[]struct {
				// Attribute ${attribute}
				Attribute *string `json:"attribute,omitempty"`

				// Id Unique ID to identify the error condition.
				Id *string `json:"id,omitempty"`

				// Message Detailed message describing the error.
				Message *string `json:"message,omitempty"`

				// Type Type of error returned.
				Type *string `json:"type,omitempty"`
			} `json:"details,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON504 = &dest

	}

	return response, nil
}

// ParseAuthSimulatorResponseResult parses an HTTP response from a AuthSimulatorWithResponse call
func ParseAuthSimulatorResponseResult(rsp *http.Response) (*AuthSimulatorResponseResult, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuthSimulatorResponseResult{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommonResponseAuthorizationSimulatorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseClearingSimulatorResponseResult parses an HTTP response from a ClearingSimulatorWithResponse call
func ParseClearingSimulatorResponseResult(rsp *http.Response) (*ClearingSimulatorResponseResult, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ClearingSimulatorResponseResult{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommonResponseClearingSimulatorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest CommonResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
