package constant

// store all user status in this file
const (
	ACTIVE                      = "ACTIVE"
	KYC_PASS                    = "KYC_PASS"
	KYC_FAIL                    = "KYC_FAIL"
	USER_CREATED                = "USER_CREATED"
	PHONE_VERIFICATION_OTP_SENT = "PHONE_VERIFICATION_OTP_SENT"
	PHONE_NUMBER_VERIFIED       = "PHONE_NUMBER_VERIFIED"
	AGE_VERIFICATION_PASSED     = "AGE_VERIFICATION_PASSED"
	AGE_VERIFICATION_FAILED     = "AGE_VERIFICATION_FAILED"
	ADDRESS_CONFIRMED           = "ADDRESS_CONFIRMED"
	PASSWORD_SET                = "PASSWORD_SET"
	AGREEMENTS_REVIEWED         = "AGREEMENTS_REVIEWED"
	CARD_AGREEMENTS_REVIEWED    = "CARD_AGREEMENTS_REVIEWED"
	MEMBERSHIP_ACCEPTED         = "MEMBERSHIP_ACCEPTED"
	ONBOARDING                  = "ONBOARDING"
)
