package constant

// store all webhook events category in this file
const (
	TRANSACTION_DEPOSIT_ALERT    = "TRANSACTION_DEPOSIT_ALERT"
	TRANSACTION_WITHDRAW_ALERT   = "TRANSACTION_WITHDRAW_ALERT"
	BENEFICIARY_ADDED            = "BENEFICIARY_ADDED"
	BENEFICIARY_DELETED_CATEGORY = "BENEFICIARY_DELETED"
	ACCOUNT_UPDATED              = "ACCOUNT_UPDATE"
	ACCOUNT_STATEMENT            = "ACCOUNT_STATEMENT"
)
